name: EUnit CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/*'
      - 'test/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:25.2.3
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit
      run: rebar3 eunit
